name: gauseva_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  google_fonts: ^3.0.0
  icons_plus: any
  firebase_auth: ^3.4.2
  firebase_core: ^1.24.0
  cloud_firestore: any
  get: ^4.6.5
  hidden_drawer_menu: ^3.0.1
  pinput: any
  salomon_bottom_bar: ^3.3.2
  image_picker: 0.8.7+1
  google_mlkit_object_detection: 0.6.0
  permission_handler: any
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  smooth_page_indicator: any
  intl: ^0.17.0
  dropdown_button2: ^2.1.0
  firebase_storage: any
  flutter_map: 2.1.0
  latlong2: ^0.8.1
  lottie: any
  carousel_slider: ^4.2.1
  upi_india: ^3.0.1
  easy_upi_payment: ^0.1.3
  paytm_allinonesdk: ^1.2.1
  carousel_indicator: ^1.0.6
  flutter_zoom_drawer: ^3.0.4
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core_platform_interface: 4.5.1


flutter:

  uses-material-design: true

  assets:
    - assets/google_logo.png
    - assets/cow_image.jpg
    - assets/upload_image.png
    - assets/models/
    - assets/bwa.png
    - assets/content.png
    - assets/mc.png
    - assets/visa.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
